name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:

jobs:

  verify:
    name: Build ${{ matrix.os }} jdk${{ matrix.java }}
    if: startsWith( github.event.head_commit.message , '[maven-release-plugin] prepare release') != true

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 13 ]
        exclude:
          - os: ubuntu-latest
            java: 11

    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ matrix.os }}-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-jdk${{ matrix.java }}-

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true

      - run: mvn verify

  sonar:
    name: Build Sonar ubuntu-latest jdk11
    if: startsWith( github.event.head_commit.message , '[maven-release-plugin] prepare release') != true

    needs: verify

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-jdk11-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-jdk11-

      - uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonar-cache
          restore-keys: sonar-cache

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true
          properties: '[{"sonar.login": "${env.SONAR_TOKEN}"}]'


      - run: mvn verify

      - run: mvn sonar:sonar
        if: github.repository_owner == 's4u'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Build Deploy ubuntu-latest jdk8
    if: >
      startsWith( github.event.head_commit.message , '[maven-release-plugin] prepare release') != true
      && github.repository_owner == 's4u'
      && github.ref == 'refs/heads/master'

    needs: sonar

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-jdk8-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-jdk8-deploy-

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true
          servers: '[{"id": "ossrh", "username": "${env.OSS_USER}", "password": "${env.OSS_PASS}"}]'

      - run: mvn deploy -Dmaven.test.skip=true
        env:
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASS: ${{ secrets.OSS_PASS }}
